org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.10
parchment_mappings_version=2025.10.12
minecraft_version=1.21.11
minecraft_version_range=[1.21.11]
neo_version=21.11.6-beta

mod_id=refactorskyblock
mod_name=Refactor Skyblock
mod_license=MIT
mod_version=0.0.3
mod_group_id=com.photosynthesisstudio.refactorskyblock
mod_authors=dalao_mengcha, Black_Moss
mod_description=